"""Interface templates for the offline mock coder: ``app.py`` and ``bot.py``.

They sit on top of the agent core :mod:`father_agent.templates` writes, and use
only what that core defines: ``Settings.from_env()``, ``build_agent()``,
``run_once()``, ``store.load()`` and ``close()``. A real model writes these
files from the coder prompts instead; the templates exist so the offline path
renders every interface (web, telegram, api) with no key and no network.
"""

from __future__ import annotations

from string import Template

from .spec import SubAgentSpec

# --------------------------------------------------------------------------- #
# web · streamlit
# --------------------------------------------------------------------------- #

_STREAMLIT = Template('''\
"""${name}: a Streamlit dashboard over the agent core in agent.py.

Generated by the Father Agent from the command:
    ${command}

Each visit (and every "Fetch now") runs one agent cycle; the chart and the
table read the stored history. Run it locally:
    streamlit run app.py
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime, timezone
from typing import Any

import streamlit as st
from dotenv import load_dotenv

from agent import Settings, StoreError, build_agent

logger = logging.getLogger("${slug}.app")

TITLE = "${name}"
VALUE_LABEL = "${value_label}"


class LastError(logging.Handler):
    """Remembers the last error the agent logged, so the page can show it."""

    def __init__(self) -> None:
        """Start with no error recorded."""
        super().__init__(level=logging.ERROR)
        self.message = ""

    def emit(self, record: logging.LogRecord) -> None:
        """Keep the formatted message of the latest error."""
        self.message = record.getMessage()


def summarise(records: list[dict[str, Any]]) -> dict[str, Any]:
    """Latest value, first value, percentage change and count, for the metric row."""
    if not records:
        return {"latest": None, "first": None, "change_pct": None, "count": 0, "updated": ""}
    latest, first = float(records[-1]["value"]), float(records[0]["value"])
    change = None if first == 0 else (latest - first) / abs(first) * 100
    return {"latest": latest, "first": first, "change_pct": change, "count": len(records),
            "updated": str(records[-1].get("timestamp", ""))}


def chart_data(records: list[dict[str, Any]]) -> dict[str, list[float]]:
    """Values in time order, keyed by their label, for ``st.line_chart``."""
    return {VALUE_LABEL: [float(r["value"]) for r in records]}


async def refresh(settings: Settings) -> tuple[dict[str, Any] | None, list[dict[str, Any]], str]:
    """Run one agent cycle; return the new record (or None), the history and any error."""
    watcher = LastError()
    logging.getLogger("${slug}").addHandler(watcher)
    agent = build_agent(settings)
    record: dict[str, Any] | None = None
    history: list[dict[str, Any]] = []
    try:
        record = await agent.run_once()
        history = agent.store.load()
    except StoreError as exc:
        watcher.message = f"history unavailable: {exc}"
    finally:
        await agent.close()
        logging.getLogger("${slug}").removeHandler(watcher)
    return record, history, watcher.message


def render() -> None:
    """Draw the dashboard: one finding, three metrics, the chart and recent readings."""
    load_dotenv()
    st.set_page_config(page_title=TITLE, page_icon="📈", layout="wide")
    settings = Settings.from_env()
    st.title(TITLE)
    st.caption("${summary_short}")

    if st.button("Fetch now", type="primary") or "history" not in st.session_state:
        try:
            record, history, error = asyncio.run(refresh(settings))
        except RuntimeError as exc:
            record, history, error = None, st.session_state.get("history", []), str(exc)
        st.session_state.update(history=history, error=error, changed=record is not None,
                                checked=datetime.now(timezone.utc).strftime("%H:%M:%S UTC"))

    history = st.session_state.get("history", [])
    if st.session_state.get("error"):
        st.error(st.session_state["error"])
    facts = summarise(history)
    status = "new reading stored" if st.session_state.get("changed") else "no change"
    st.caption(f"checked {st.session_state.get('checked', '-')} · {status} · "
               f"target {settings.target or '(set ${target_env})'}")
    if not history:
        st.info("No readings yet. Set ${target_env} in .env and press Fetch now.")
        return

    latest, first, change = facts["latest"], facts["first"], facts["change_pct"]
    left, middle, right = st.columns(3)
    left.metric(f"{VALUE_LABEL} now", f"{latest:,.4f}",
                None if change is None else f"{change:+.1f}%")
    middle.metric("readings stored", f"{facts['count']:,}")
    right.metric("first reading", f"{first:,.4f}")
    st.subheader(f"{VALUE_LABEL} over time")
    st.line_chart(chart_data(history))
    st.subheader("Recent readings")
    st.dataframe([{"time (UTC)": r.get("timestamp", ""), VALUE_LABEL: r.get("value")}
                  for r in reversed(history[-20:])])
    st.caption(f"Built by the Father Agent · runs every {settings.interval_seconds}s "
               f"with python agent.py · history in {settings.data_dir}")


if __name__ == "__main__":
    render()
''')

# --------------------------------------------------------------------------- #
# web · fastapi and api · fastapi (the web flavour adds an HTML dashboard)
# --------------------------------------------------------------------------- #

_FASTAPI = Template('''\
"""${name}: ${kind} over the agent core in agent.py.

Generated by the Father Agent from the command:
    ${command}

Endpoints: GET /health, POST /run (one agent cycle), GET /history, GET /latest${index_doc}.
Set ${upper}_AUTORUN=1 to also run the agent on its schedule in the background.
Run it locally:
    python app.py            # http://127.0.0.1:${port}
"""

from __future__ import annotations

import argparse
import asyncio
import contextlib
${html_import}import logging
import os
from collections.abc import AsyncIterator, Callable
from typing import Any

import uvicorn
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
${response_import}
from agent import Settings, StoreError, build_agent

logger = logging.getLogger("${slug}.app")

TITLE = "${name}"
VALUE_LABEL = "${value_label}"


def default_agent() -> Any:
    """Build the real agent from the environment (and .env, when present)."""
    load_dotenv()
    return build_agent(Settings.from_env())


def create_app(agent_factory: Callable[[], Any] = default_agent) -> FastAPI:
    """Create the FastAPI app; ``agent_factory`` lets tests pass a fake agent."""
    state: dict[str, Any] = {}
    lock = asyncio.Lock()

    @contextlib.asynccontextmanager
    async def lifespan(_: FastAPI) -> AsyncIterator[None]:
        state["agent"] = agent_factory()
        task = None
        if os.environ.get("${upper}_AUTORUN", "") == "1":
            task = asyncio.create_task(state["agent"].run_forever())
        try:
            yield
        finally:
            if task is not None:
                task.cancel()
                with contextlib.suppress(asyncio.CancelledError):
                    await task
            await state["agent"].close()

    app = FastAPI(title=TITLE, version="1.0.0", lifespan=lifespan)

    def history() -> list[dict[str, Any]]:
        """The stored readings, or HTTP 503 when the history cannot be read."""
        try:
            return state["agent"].store.load()
        except StoreError as exc:
            raise HTTPException(status_code=503, detail=f"history unavailable: {exc}") from exc

    @app.get("/health")
    async def health() -> dict[str, str]:
        """Liveness probe for hosts and load balancers."""
        return {"status": "ok", "agent": "${slug}"}

    @app.post("/run")
    async def run() -> dict[str, Any]:
        """Run one agent cycle now; reports whether a new reading was stored."""
        async with lock:
            try:
                record = await state["agent"].run_once()
            except StoreError as exc:
                raise HTTPException(status_code=503, detail=str(exc)) from exc
        return {"changed": record is not None, "record": record}

    @app.get("/history")
    async def get_history(limit: int = 100) -> dict[str, Any]:
        """The most recent ``limit`` readings, oldest first."""
        records = history()
        return {"count": len(records), "records": records[-max(1, min(limit, 1000)):]}

    @app.get("/latest")
    async def latest() -> dict[str, Any]:
        """The newest reading, or HTTP 404 before the first one."""
        records = history()
        if not records:
            raise HTTPException(status_code=404, detail="no readings yet; POST /run first")
        return records[-1]
${index_route}
    return app


app = create_app()
${page}

def main(argv: list[str] | None = None) -> int:
    """Serve the app with uvicorn. PORT (set by most hosts) picks the port."""
    parser = argparse.ArgumentParser(description="${name} HTTP server")
    parser.add_argument("--host", default=os.environ.get("HOST", "0.0.0.0"))
    parser.add_argument("--port", type=int, default=int(os.environ.get("PORT", "${port}")))
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    try:
        uvicorn.run(app, host=args.host, port=args.port)
    except KeyboardInterrupt:
        logger.info("stopped by user")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
''')

_INDEX_ROUTE = '''
    @app.get("/", response_class=HTMLResponse)
    async def index() -> str:
        """The dashboard page: the latest value, its change, a sparkline and recent rows."""
        return render_page(history())
'''

# The dashboard page. Colours, fonts and radii come from --app-* custom
# properties declared for both modes; data-app-mode on <html> picks one.
_PAGE = r'''

PAGE_CSS = """
:root, [data-app-mode="light"] {
  --app-bg: #f7f5ef; --app-surface: #fffdf8; --app-text: #1d1d1b; --app-muted: #6b6a64;
  --app-rule: #e3dfd3; --app-accent: #2f5fd0; --app-good: #23825a; --app-bad: #c2412f;
  --app-font: "Atkinson Hyperlegible", system-ui, -apple-system, "Segoe UI", sans-serif;
  --app-mono: "JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace;
  --app-radius: 6px; --app-shadow: none; color-scheme: light;
}
[data-app-mode="dark"] {
  --app-bg: #1b1c1e; --app-surface: #232427; --app-text: #ecebe6; --app-muted: #a3a29c;
  --app-rule: #36373b; --app-accent: #7ea2ff; --app-good: #46c08a; --app-bad: #ff7a66;
  color-scheme: dark;
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--app-bg); color: var(--app-text);
       font: 15px/1.5 var(--app-font); }
main { max-width: 1100px; margin: 0 auto; padding: 28px 20px 64px; }
header { display: flex; justify-content: space-between; gap: 12px; align-items: flex-start;
         border-bottom: 1px solid var(--app-rule); padding-bottom: 14px; }
h1 { margin: 0; font-size: 22px; letter-spacing: -0.01em; }
.sub { color: var(--app-muted); font-size: 13px; margin-top: 4px; }
button { font: 600 13px var(--app-font); color: var(--app-text); background: var(--app-surface);
         border: 1px solid var(--app-rule); border-radius: var(--app-radius);
         padding: 7px 12px; cursor: pointer; }
button.primary { background: var(--app-accent); border-color: var(--app-accent);
                 color: var(--app-bg); }
.actions { display: flex; gap: 8px; flex-wrap: wrap; }
.finding { display: flex; align-items: baseline; gap: 14px; flex-wrap: wrap; padding: 18px 0;
           border-bottom: 1px solid var(--app-rule); }
.finding b { font: 700 44px/1 var(--app-mono); font-variant-numeric: tabular-nums;
             letter-spacing: -0.03em; }
.finding span { color: var(--app-muted); }
.up { color: var(--app-good); } .down { color: var(--app-bad); }
.metrics { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));
           border-bottom: 1px solid var(--app-rule); }
.metrics div { padding: 12px 0; }
.metrics div + div { border-left: 1px solid var(--app-rule); padding-left: 14px; }
.metrics b { display: block; font: 600 20px var(--app-mono); font-variant-numeric: tabular-nums; }
.metrics small { color: var(--app-muted); font-size: 12px; }
h2 { font: 600 11px var(--app-mono); letter-spacing: .1em; text-transform: uppercase;
     color: var(--app-muted); margin: 24px 0 8px; }
svg.spark { width: 100%; height: 120px; display: block; }
svg.spark polyline { fill: none; stroke: var(--app-accent); stroke-width: 2; }
table { width: 100%; border-collapse: collapse; font-size: 13px; }
td, th { text-align: left; padding: 7px 0; border-top: 1px solid var(--app-rule); }
th { color: var(--app-muted); font-weight: 600; }
td.num, th.num { text-align: right; font-family: var(--app-mono);
                 font-variant-numeric: tabular-nums; }
.empty { color: var(--app-muted); padding: 24px 0; }
footer { color: var(--app-muted); font-size: 12px; margin-top: 28px; }
code { font-family: var(--app-mono); font-size: .95em; }
@media (max-width: 560px) {
  header { flex-direction: column; }
  .finding b { font-size: 36px; }
  .metrics { grid-template-columns: 1fr; }
  .metrics div + div { border-left: 0; padding-left: 0; border-top: 1px solid var(--app-rule); }
}
"""

# Mode: ?mode=light|dark, then the saved choice, then the device setting.
PAGE_JS = """
(function () {
  var root = document.documentElement, saved = null, q = null;
  try { q = new URLSearchParams(location.search).get('mode'); saved = localStorage.getItem('app-mode'); } catch (e) {}
  var mode = q === 'light' || q === 'dark' ? q : saved;
  if (mode !== 'light' && mode !== 'dark') mode = matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  root.setAttribute('data-app-mode', mode);
  window.toggleMode = function () {
    var next = root.getAttribute('data-app-mode') === 'dark' ? 'light' : 'dark';
    root.setAttribute('data-app-mode', next);
    try { localStorage.setItem('app-mode', next); } catch (e) {}
  };
  window.fetchNow = function (button) {
    button.disabled = true; button.textContent = 'Fetching...';
    fetch('run', { method: 'POST' }).then(function () { location.reload(); },
      function () { button.disabled = false; button.textContent = 'Fetch now'; });
  };
})();
"""


def sparkline(values: list[float], width: int = 600, height: int = 120) -> str:
    """An inline SVG polyline of ``values`` (empty with fewer than two points)."""
    if len(values) < 2:
        return ""
    low, high = min(values), max(values)
    span = (high - low) or 1.0
    step = width / (len(values) - 1)
    points = " ".join(f"{i * step:.1f},{height - 6 - (v - low) / span * (height - 12):.1f}"
                      for i, v in enumerate(values))
    return (f'<svg class="spark" viewBox="0 0 {width} {height}" preserveAspectRatio="none" '
            f'role="img" aria-label="{html.escape(VALUE_LABEL)} over time">'
            f'<polyline points="{points}"/></svg>')


def render_page(records: list[dict[str, Any]]) -> str:
    """The whole dashboard as one HTML document; every value is escaped."""
    esc = html.escape
    if records:
        values = [float(r["value"]) for r in records]
        latest, first = values[-1], values[0]
        change = None if first == 0 else (latest - first) / abs(first) * 100
        trend = "" if change is None else (
            f'<span class="{"up" if change >= 0 else "down"}">{change:+.1f}% since the first '
            f"reading</span>")
        rows = "".join(f'<tr><td>{esc(str(r.get("timestamp", "")))}</td>'
                       f'<td class="num">{float(r["value"]):,.4f}</td></tr>'
                       for r in reversed(records[-20:]))
        body = (f'<section class="finding"><b>{latest:,.4f}</b><span>{esc(VALUE_LABEL)} now'
                f"</span>{trend}</section>"
                f'<section class="metrics"><div><b>{len(records):,}</b><small>readings stored'
                f'</small></div><div><b>{first:,.4f}</b><small>first reading</small></div>'
                f'<div><b>{max(values):,.4f}</b><small>highest</small></div></section>'
                f"<h2>{esc(VALUE_LABEL)} over time</h2>{sparkline(values)}"
                f'<h2>Recent readings</h2><table><tr><th>time (UTC)</th>'
                f'<th class="num">{esc(VALUE_LABEL)}</th></tr>{rows}</table>')
        updated = esc(str(records[-1].get("timestamp", "")))
    else:
        body = ('<p class="empty">No readings yet. Set the variables in <code>.env</code> and '
                "press <b>Fetch now</b>.</p>")
        updated = "never"
    return (f'<!doctype html><html lang="en" data-app-mode="light"><head><meta charset="utf-8">'
            f'<meta name="viewport" content="width=device-width, initial-scale=1">'
            f"<title>{esc(TITLE)}</title><style>{PAGE_CSS}</style><script>{PAGE_JS}</script>"
            f"</head><body><main><header><div><h1>{esc(TITLE)}</h1>"
            f'<div class="sub">last reading {updated}</div></div><div class="actions">'
            f'<button class="primary" onclick="fetchNow(this)">Fetch now</button>'
            f'<button onclick="toggleMode()" aria-label="Toggle light and dark">Light / dark'
            f"</button></div></header>{body}<footer>Built by the Father Agent · JSON at "
            f'<a href="history">/history</a> · <a href="docs">/docs</a></footer></main>'
            f"</body></html>")

'''

# --------------------------------------------------------------------------- #
# telegram · aiogram
# --------------------------------------------------------------------------- #

_BOT = Template('''\
"""${name}: an aiogram 3 Telegram bot over the agent core in agent.py.

Generated by the Father Agent from the command:
    ${command}

It runs the agent every ${interval}s and DMs every subscribed chat when a new
reading is stored; /status and /check answer on demand.

    python bot.py               # long polling, for your laptop
    python bot.py --webhook     # aiohttp webhook server, for a host (Render)
    python bot.py --dry-run     # build the dispatcher and exit: no token, no network

BOT_TOKEN is read from the environment or .env at start-up, never from source.
"""

from __future__ import annotations

import argparse
import asyncio
import contextlib
import json
import logging
import os
from collections.abc import Awaitable, Callable
from pathlib import Path
from typing import Any

from aiogram import BaseMiddleware, Bot, Dispatcher, Router
from aiogram.exceptions import TelegramAPIError
from aiogram.filters import Command, CommandStart
from aiogram.types import Message, TelegramObject
from aiogram.webhook.aiohttp_server import SimpleRequestHandler, setup_application
from aiohttp import web
from dotenv import load_dotenv

from agent import Settings, StoreError, build_agent

logger = logging.getLogger("${slug}.bot")

#: Command menu; scripts/setup_bot.py registers it with Telegram.
BOT_COMMANDS: list[tuple[str, str]] = [
    ("start", "subscribe this chat to alerts"),
    ("status", "latest ${value_label} and when it was read"),
    ("check", "run one check right now"),
    ("stop", "unsubscribe this chat"),
]
WEBHOOK_PATH = "/telegram/webhook"
VALUE_LABEL = "${value_label}"


class BotConfig:
    """Bot settings from the environment: token, chats, access list and webhook."""

    def __init__(self) -> None:
        """Read BOT_TOKEN, TELEGRAM_CHAT_ID, ALLOWED_USER_IDS, WEBHOOK_* and PORT."""
        self.token = os.environ.get("BOT_TOKEN", "")
        self.chat_id = os.environ.get("TELEGRAM_CHAT_ID", "")
        raw = os.environ.get("ALLOWED_USER_IDS", "")
        self.allowed = {int(part) for part in raw.replace(" ", "").split(",") if part.isdigit()}
        self.webhook_base = (os.environ.get("WEBHOOK_BASE_URL")
                             or os.environ.get("RENDER_EXTERNAL_URL") or "").rstrip("/")
        self.webhook_secret = os.environ.get("WEBHOOK_SECRET", "")
        self.port = int(os.environ.get("PORT", "8080"))


class Subscribers:
    """Chat ids that receive alerts, kept in ``<data_dir>/subscribers.json``."""

    def __init__(self, data_dir: Path, fixed: str = "") -> None:
        """Load saved chats; ``fixed`` (TELEGRAM_CHAT_ID) always receives alerts."""
        self.path = data_dir / "subscribers.json"
        self.fixed = {int(fixed)} if fixed.lstrip("-").isdigit() else set()
        self.chats: set[int] = set()
        try:
            self.chats = {int(c) for c in json.loads(self.path.read_text(encoding="utf-8"))}
        except FileNotFoundError:
            pass
        except (OSError, ValueError, TypeError) as exc:
            logger.warning("ignoring unreadable %s: %s", self.path, exc)

    def all(self) -> set[int]:
        """Every chat to alert."""
        return self.chats | self.fixed

    def add(self, chat_id: int) -> None:
        """Subscribe a chat and save the list."""
        self.chats.add(chat_id)
        self._save()

    def remove(self, chat_id: int) -> None:
        """Unsubscribe a chat and save the list."""
        self.chats.discard(chat_id)
        self._save()

    def _save(self) -> None:
        """Write the list; a failure is logged, never raised into a handler."""
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            self.path.write_text(json.dumps(sorted(self.chats)), encoding="utf-8")
        except OSError as exc:
            logger.warning("could not save subscribers: %s", exc)


class AccessMiddleware(BaseMiddleware):
    """Drops messages from users outside ALLOWED_USER_IDS (when it is set)."""

    def __init__(self, allowed: set[int]) -> None:
        """Remember the allowed user ids; an empty set allows everyone."""
        self.allowed = allowed

    async def __call__(self, handler: Callable[[TelegramObject, dict[str, Any]], Awaitable[Any]],
                       event: TelegramObject, data: dict[str, Any]) -> Any:
        """Pass the update on only when its sender is allowed."""
        user = data.get("event_from_user")
        if self.allowed and (user is None or user.id not in self.allowed):
            logger.warning("ignored a message from user %s", getattr(user, "id", "?"))
            return None
        return await handler(event, data)


def format_reading(record: dict[str, Any] | None) -> str:
    """One line describing a reading, for /status and alerts."""
    if not record:
        return "No readings yet."
    return f"{VALUE_LABEL}: {float(record['value']):,.4f} (read {record.get('timestamp', '?')})"


def format_alert(record: dict[str, Any], before: dict[str, Any] | None) -> str:
    """The message sent when the agent stores a new reading."""
    if before is None:
        return f"Watching started. {format_reading(record)}"
    return (f"Changed: {float(before['value']):,.4f} → {float(record['value']):,.4f} "
            f"{VALUE_LABEL}")


def build_dispatcher(agent: Any, subscribers: Subscribers, allowed: set[int]) -> Dispatcher:
    """Register the command handlers and the access middleware on a fresh dispatcher."""
    router = Router(name="${slug}")
    router.message.middleware(AccessMiddleware(allowed))

    @router.message(CommandStart())
    async def start(message: Message) -> None:
        """Subscribe the chat and say what the bot does."""
        subscribers.add(message.chat.id)
        await message.answer("Subscribed. I will message you when ${value_label} changes. "
                             "/status for the latest reading, /stop to unsubscribe.")

    @router.message(Command("status"))
    async def status(message: Message) -> None:
        """Reply with the latest stored reading."""
        try:
            last = agent.store.last()
        except StoreError as exc:
            logger.error("history unavailable: %s", exc)
            last = None
        await message.answer(f"{format_reading(last)}\\nChecking every "
                             f"{agent.settings.interval_seconds}s; "
                             f"{len(subscribers.all())} chat(s) subscribed.")

    @router.message(Command("check"))
    async def check(message: Message) -> None:
        """Run one agent cycle now and report the result."""
        record = await agent.run_once()
        await message.answer(format_reading(record) if record else
                             "No change since the last reading (or the source is down).")

    @router.message(Command("stop"))
    async def stop(message: Message) -> None:
        """Unsubscribe the chat."""
        subscribers.remove(message.chat.id)
        await message.answer("Unsubscribed. /start to subscribe again.")

    dispatcher = Dispatcher()
    dispatcher.include_router(router)
    return dispatcher


async def watch(bot: Bot, agent: Any, subscribers: Subscribers) -> None:
    """Run the agent on its schedule and alert every subscriber on a change."""
    while True:
        try:
            before = agent.store.last()
        except StoreError:
            before = None
        record = await agent.run_once()
        if record is not None:
            for chat_id in subscribers.all():
                try:
                    await bot.send_message(chat_id, format_alert(record, before))
                except TelegramAPIError as exc:
                    logger.warning("could not alert chat %s: %s", chat_id, exc)
        await asyncio.sleep(agent.settings.interval_seconds)


def wire(dispatcher: Dispatcher, agent: Any, subscribers: Subscribers) -> None:
    """Start the watcher with the bot and stop it (and the agent) on shutdown."""
    tasks: list[asyncio.Task[None]] = []

    async def on_startup(bot: Bot) -> None:
        tasks.append(asyncio.create_task(watch(bot, agent, subscribers)))

    async def on_shutdown() -> None:
        for task in tasks:
            task.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await task
        await agent.close()

    dispatcher.startup.register(on_startup)
    dispatcher.shutdown.register(on_shutdown)


async def run_polling(config: BotConfig, agent: Any, subscribers: Subscribers) -> None:
    """Long polling: no public URL needed, ideal on a laptop."""
    bot = Bot(token=config.token)
    dispatcher = build_dispatcher(agent, subscribers, config.allowed)
    wire(dispatcher, agent, subscribers)
    try:
        await bot.delete_webhook(drop_pending_updates=False)
        await dispatcher.start_polling(bot)
    except TelegramAPIError as exc:
        logger.error("Telegram refused the bot: %s", exc)
    finally:
        await bot.session.close()


def run_webhook(config: BotConfig, agent: Any, subscribers: Subscribers) -> None:
    """Webhook mode: an aiohttp server Telegram calls; GET /health for the host."""
    bot = Bot(token=config.token)
    dispatcher = build_dispatcher(agent, subscribers, config.allowed)
    wire(dispatcher, agent, subscribers)

    async def set_hook(bot: Bot) -> None:
        url = config.webhook_base + WEBHOOK_PATH
        try:
            await bot.set_webhook(url, secret_token=config.webhook_secret or None)
            logger.info("webhook set: %s", url)
        except TelegramAPIError as exc:
            logger.error("could not set the webhook: %s", exc)

    async def health(_: web.Request) -> web.Response:
        return web.json_response({"status": "ok", "agent": "${slug}"})

    dispatcher.startup.register(set_hook)
    app = web.Application()
    app.router.add_get("/health", health)
    SimpleRequestHandler(dispatcher=dispatcher, bot=bot,
                         secret_token=config.webhook_secret or None).register(app,
                                                                             path=WEBHOOK_PATH)
    setup_application(app, dispatcher, bot=bot)
    web.run_app(app, host="0.0.0.0", port=config.port)


def main(argv: list[str] | None = None) -> int:
    """Parse flags, read the config and run the bot in polling or webhook mode."""
    parser = argparse.ArgumentParser(description="${name} Telegram bot")
    parser.add_argument("--webhook", action="store_true", help="serve a webhook (for a host)")
    parser.add_argument("--dry-run", action="store_true",
                        help="build the dispatcher, report it and exit (no token needed)")
    parser.add_argument("-v", "--verbose", action="store_true", help="debug logging")
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO,
                        format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    load_dotenv()
    config = BotConfig()
    settings = Settings.from_env()
    agent = build_agent(settings)
    subscribers = Subscribers(settings.data_dir, config.chat_id)

    if args.dry_run:
        dispatcher = build_dispatcher(agent, subscribers, config.allowed)
        handlers = sum(len(r.message.handlers) for r in dispatcher.chain_tail)
        logger.info("dry run: %d handlers (%s), access list %s, token %s, mode %s",
                    handlers, ", ".join(f"/{n}" for n, _ in BOT_COMMANDS),
                    sorted(config.allowed) or "open", "set" if config.token else "missing",
                    "webhook" if args.webhook or config.webhook_base else "polling")
        asyncio.run(agent.close())
        return 0
    if not config.token:
        logger.error("set BOT_TOKEN (from @BotFather) in .env or the environment")
        return 2
    try:
        if args.webhook:
            if not config.webhook_base:
                logger.error("webhook mode needs WEBHOOK_BASE_URL (or RENDER_EXTERNAL_URL)")
                return 2
            run_webhook(config, agent, subscribers)
        else:
            asyncio.run(run_polling(config, agent, subscribers))
    except KeyboardInterrupt:
        logger.info("stopped by user")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
''')

# --------------------------------------------------------------------------- #
# Interface tests, appended to test_agent.py
# --------------------------------------------------------------------------- #

_TESTS_STREAMLIT = Template('''

def test_dashboard_summarises_history() -> None:
    """The dashboard's metric row reads latest, first, change and count from history."""
    pytest.importorskip("streamlit")
    pytest.importorskip("dotenv")
    from app import chart_data, summarise

    records = [make_record(2.0, {}), make_record(3.0, {})]
    facts = summarise(records)
    assert facts["latest"] == 3.0 and facts["count"] == 2
    assert facts["change_pct"] == pytest.approx(50.0)
    assert summarise([])["latest"] is None
    assert list(chart_data(records).values()) == [[2.0, 3.0]]
''')

_TESTS_FASTAPI = Template('''

def test_http_app_runs_the_agent(tmp_path: Any) -> None:
    """GET /health answers; POST /run runs one cycle; /history and /latest read it back."""
    pytest.importorskip("fastapi")
    pytest.importorskip("httpx")
    pytest.importorskip("dotenv")
    from fastapi.testclient import TestClient

    from app import create_app

    agent = make_agent(tmp_path, [4.0, 4.0])
    with TestClient(create_app(lambda: agent)) as client:
        assert client.get("/health").json()["status"] == "ok"
        assert client.get("/latest").status_code == 404
        assert client.post("/run").json()["changed"] is True
        assert client.post("/run").json()["changed"] is False
        assert client.get("/history").json()["count"] == 1
        assert client.get("/latest").json()["value"] == 4.0${index_test}
    assert agent.client.closed
''')

_INDEX_TEST = '''
        page = client.get("/")
        assert page.status_code == 200 and "data-app-mode" in page.text'''

_TESTS_TELEGRAM = Template('''

def test_bot_builds_without_a_token(tmp_path: Any, monkeypatch: pytest.MonkeyPatch) -> None:
    """--dry-run builds the dispatcher with every handler and needs no token or network."""
    pytest.importorskip("aiogram")
    pytest.importorskip("dotenv")
    import bot

    monkeypatch.delenv("BOT_TOKEN", raising=False)
    monkeypatch.setenv("${upper}_DATA_DIR", str(tmp_path))
    assert bot.main(["--dry-run"]) == 0
    agent = make_agent(tmp_path, [1.0])
    dispatcher = bot.build_dispatcher(agent, bot.Subscribers(tmp_path), set())
    handlers = sum(len(r.message.handlers) for r in dispatcher.chain_tail)
    assert handlers == len(bot.BOT_COMMANDS)


def test_bot_messages_and_subscribers(tmp_path: Any) -> None:
    """Alerts describe the change; subscribers persist across restarts."""
    pytest.importorskip("aiogram")
    pytest.importorskip("dotenv")
    from bot import Subscribers, format_alert

    before, after = make_record(1.0, {}), make_record(2.5, {})
    assert "1.0000" in format_alert(after, before) and "2.5000" in format_alert(after, before)
    assert format_alert(after, None).startswith("Watching started")
    subs = Subscribers(tmp_path, fixed="42")
    subs.add(7)
    assert Subscribers(tmp_path).all() == {7}
    assert subs.all() == {7, 42}
''')


def _values(spec: SubAgentSpec, base: dict[str, str]) -> dict[str, str]:
    """Template values: the agent layout's, plus the interface's own."""
    web = spec.delivery.interface == "web"
    return {**base, "port": "8000",
            "kind": "a FastAPI dashboard" if web else "a FastAPI JSON service",
            "index_doc": " and GET / (the dashboard page)" if web else "",
            "index_route": _INDEX_ROUTE if web else "",
            "page": _PAGE if web else "",
            "html_import": "import html\n" if web else "",
            "response_import": "from fastapi.responses import HTMLResponse\n" if web else "",
            "index_test": _INDEX_TEST if web else ""}


def render_interface(spec: SubAgentSpec, base: dict[str, str]) -> str:
    """Render ``app.py`` or ``bot.py`` for ``spec`` (``base``: the agent layout's values)."""
    framework = spec.delivery.framework
    values = _values(spec, base)
    if framework == "streamlit":
        return _STREAMLIT.substitute(values)
    if framework == "fastapi":
        return _FASTAPI.substitute(values)
    if framework == "aiogram":
        return _BOT.substitute(values)
    raise ValueError(f"no interface template for {spec.delivery.label}")


def render_interface_tests(spec: SubAgentSpec, base: dict[str, str]) -> str:
    """Tests for the interface file, appended to test_agent.py (empty for cli)."""
    template = {"streamlit": _TESTS_STREAMLIT, "fastapi": _TESTS_FASTAPI,
                "aiogram": _TESTS_TELEGRAM}.get(spec.delivery.framework)
    return template.substitute(_values(spec, base)) if template else ""
