"""Code templates for the offline mock coder, plus the README renderer.

The mock provider uses :func:`render_agent` and :func:`render_tests` to write
real, lint-clean sub-agents from a spec without a model. Every template
follows the same standards the prompts demand of a real model: asyncio,
classes with docstrings, ``logging`` instead of ``print``, try/except around
every external call, and real libraries. :func:`render_readme` is used for
every sub-agent, whichever provider wrote the code.
"""

from __future__ import annotations

import textwrap
from string import Template

from .heuristics import DEFAULT_PROFILE, PROFILES, Profile, choose_profile
from .spec import SubAgentSpec

# --------------------------------------------------------------------------- #
# Shared skeleton
# --------------------------------------------------------------------------- #

_HEADER = Template('''\
"""${name}: ${summary_line}

Generated by the Father Agent from the command:
    ${command}

Run it once:
    ${run_example}
Run it on a schedule (every ${interval}s by default):
    ${run_forever}
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import logging
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

${third_party}

logger = logging.getLogger("${slug}")


class SourceError(Exception):
    """Raised when the data source cannot be read."""


class StoreError(Exception):
    """Raised when history cannot be read or written."""


def make_record(value: float, details: dict[str, Any]) -> dict[str, Any]:
    """Build one history record; the fingerprint ignores the timestamp."""
    fingerprint = hashlib.sha256(
        json.dumps({"value": value, "details": details}, sort_keys=True, default=str).encode()
    ).hexdigest()[:16]
    return {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "value": float(value),
        "fingerprint": fingerprint,
        "details": details,
    }


@dataclass
class Settings:
    """Runtime settings, read from environment variables with safe defaults."""

    target: str = "${default_target}"
    interval_seconds: int = ${interval}
    data_dir: Path = field(default_factory=lambda: Path("${slug}_data"))
    timeout_seconds: float = 20.0

    @classmethod
    def from_env(cls) -> Settings:
        """Build settings from ${target_env}, ${upper}_INTERVAL and ${upper}_DATA_DIR."""
        return cls(
            target=os.environ.get("${target_env}", "${default_target}"),
            interval_seconds=int(os.environ.get("${upper}_INTERVAL", "${interval}")),
            data_dir=Path(os.environ.get("${upper}_DATA_DIR", "${slug}_data")),
        )
''')

_STORE = Template('''

class ${store}:
    """Appends records to a JSON Lines file and reads the history back."""

    def __init__(self, data_dir: Path) -> None:
        """Keep history in ``<data_dir>/history.jsonl``."""
        self.path = data_dir / "history.jsonl"

    def append(self, record: dict[str, Any]) -> None:
        """Append one record, creating the folder on first use."""
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with self.path.open("a", encoding="utf-8") as handle:
                handle.write(json.dumps(record, default=str) + "\\n")
        except OSError as exc:
            raise StoreError(f"cannot write {self.path}: {exc}") from exc

    def load(self) -> list[dict[str, Any]]:
        """Return every stored record, skipping corrupt lines."""
        if not self.path.exists():
            return []
        records: list[dict[str, Any]] = []
        try:
            with self.path.open(encoding="utf-8") as handle:
                for number, raw in enumerate(handle, start=1):
                    text = raw.strip()
                    if not text:
                        continue
                    try:
                        records.append(json.loads(text))
                    except json.JSONDecodeError:
                        logger.warning("skipping corrupt line %d in %s", number, self.path)
        except OSError as exc:
            raise StoreError(f"cannot read {self.path}: {exc}") from exc
        return records

    def last(self) -> dict[str, Any] | None:
        """Return the most recent record, or None when history is empty."""
        history = self.load()
        return history[-1] if history else None
''')

_PLOTTER = Template('''

class ${plotter}:
    """Draws the recorded values over time to a PNG chart."""

    def __init__(self, output_path: Path, title: str) -> None:
        """Remember where to save the chart and what to call it."""
        self.output_path = output_path
        self.title = title

    def plot(self, records: list[dict[str, Any]]) -> Path | None:
        """Render ``records`` to ``output_path``; returns None with fewer than 2 points."""
        if len(records) < 2:
            return None
        frame = pd.DataFrame(records)
        frame["timestamp"] = pd.to_datetime(frame["timestamp"])
        figure, axis = plt.subplots(figsize=(9, 4))
        try:
            axis.plot(frame["timestamp"], frame["value"], marker="o", linewidth=1.5)
            axis.set_title(self.title)
            axis.set_xlabel("time (UTC)")
            axis.set_ylabel("${value_label}")
            axis.grid(alpha=0.3)
            figure.autofmt_xdate()
            self.output_path.parent.mkdir(parents=True, exist_ok=True)
            figure.savefig(self.output_path, dpi=120, bbox_inches="tight")
        finally:
            plt.close(figure)
        return self.output_path
''')

_MAIN = Template('''

class ${main}:
    """${summary_line}"""

    def __init__(self, settings: Settings, client: Any, store: ${store},
                 plotter: ${plotter_type} = None) -> None:
        """Wire the agent to its data source, history store and optional chart."""
        self.settings = settings
        self.client = client
        self.store = store
        self.plotter = plotter

    async def run_once(self) -> dict[str, Any] | None:
        """Fetch one reading and store it if it changed.

        Returns:
            The new record when something changed, otherwise None.
        """
        try:
            record = await self.client.fetch()
        except SourceError as exc:
            logger.error("fetch failed: %s", exc)
            return None
        try:
            previous = self.store.last()
            if previous and previous.get("fingerprint") == record["fingerprint"]:
                logger.info("no change (${value_label}=%s)", record["value"])
                return None
            self.store.append(record)
        except StoreError as exc:
            logger.error("history unavailable: %s", exc)
            return None
        before = previous.get("value") if previous else None
        logger.info("change recorded: ${value_label}=%s (was %s)", record["value"], before)
        if self.plotter is not None:
            try:
                chart = await asyncio.to_thread(self.plotter.plot, self.store.load())
                if chart:
                    logger.info("chart updated: %s", chart)
            except (OSError, ValueError, StoreError) as exc:
                logger.warning("could not draw the chart: %s", exc)
        return record

    async def run_forever(self) -> None:
        """Run ``run_once`` every ``interval_seconds`` until cancelled."""
        logger.info("starting: every %ss", self.settings.interval_seconds)
        try:
            while True:
                await self.run_once()
                await asyncio.sleep(self.settings.interval_seconds)
        finally:
            await self.close()

    async def close(self) -> None:
        """Release the data source's resources."""
        try:
            await self.client.aclose()
        except Exception as exc:  # noqa: BLE001 - closing must never mask the real error
            logger.debug("error while closing the client: %s", exc)


def build_agent(settings: Settings) -> ${main}:
    """Create the agent with its real data source${plot_note}."""
    return ${main}(
        settings,
        ${client}(settings),
        ${store}(settings.data_dir),
        ${plotter_ctor},
    )


def main(argv: list[str] | None = None) -> int:
    """Command-line entry point. Returns a process exit code."""
    parser = argparse.ArgumentParser(description="${name}: ${summary_short}")
    parser.add_argument("--once", action="store_true", help="run a single cycle and exit")
    parser.add_argument("--interval", type=int, help="seconds between cycles")
    parser.add_argument("--target", help="override ${target_env}")
    parser.add_argument("-v", "--verbose", action="store_true", help="debug logging")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO,
                        format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    settings = Settings.from_env()
    if args.interval:
        settings.interval_seconds = args.interval
    if args.target:
        settings.target = args.target

    agent = build_agent(settings)

    async def _run() -> None:
        if args.once:
            try:
                await agent.run_once()
            finally:
                await agent.close()
        else:
            await agent.run_forever()

    try:
        asyncio.run(_run())
    except KeyboardInterrupt:
        logger.info("stopped by user")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
''')

# --------------------------------------------------------------------------- #
# Data sources, one per specialisation
# --------------------------------------------------------------------------- #

_CLIENT_RPC = Template('''

class ${client}:
    """Reads a wallet balance over ${chain} JSON-RPC (a free public node by default)."""

    def __init__(self, settings: Settings) -> None:
        """Create the HTTP client for the configured RPC endpoint."""
        self.settings = settings
        self.rpc_url = os.environ.get("${rpc_env}", "${rpc_default}")
        self._http = httpx.AsyncClient(timeout=settings.timeout_seconds)

    async def fetch(self) -> dict[str, Any]:
        """Return the current balance of ``settings.target`` as a record."""
        if not self.settings.target:
            raise SourceError("set ${target_env} to the wallet address you want to watch")
        payload = {"jsonrpc": "2.0", "id": 1, "method": "${rpc_method}",
                   "params": ${rpc_params}}
        try:
            response = await self._http.post(self.rpc_url, json=payload)
            response.raise_for_status()
            body = response.json()
        except (httpx.HTTPError, ValueError) as exc:
            raise SourceError(f"RPC request to {self.rpc_url} failed: {exc}") from exc
        if body.get("error"):
            raise SourceError(f"RPC error: {body['error']}")
        try:
            raw = ${rpc_extract}
        except (KeyError, TypeError, ValueError) as exc:
            raise SourceError(f"unexpected RPC payload: {body}") from exc
        balance = raw / ${rpc_divisor}
        return make_record(balance, {"address": self.settings.target, "raw": str(raw),
                                     "unit": "${rpc_unit}"})

    async def aclose(self) -> None:
        """Close the HTTP connection pool."""
        await self._http.aclose()
''')

_CLIENT_HTML = Template('''

class ${client}:
    """Downloads a page and collects the text of every element matching a CSS selector."""

    def __init__(self, settings: Settings) -> None:
        """Create the HTTP client and read the selector from CSS_SELECTOR."""
        self.settings = settings
        self.selector = os.environ.get("CSS_SELECTOR", "h2")
        self._http = httpx.AsyncClient(
            timeout=settings.timeout_seconds,
            follow_redirects=True,
            headers={"User-Agent": "${slug}/1.0 (+https://github.com/father-agent)"},
        )

    async def fetch(self) -> dict[str, Any]:
        """Return the matching items on ``settings.target`` as a record."""
        if not self.settings.target:
            raise SourceError("set ${target_env} to the page you want to scrape")
        try:
            response = await self._http.get(self.settings.target)
            response.raise_for_status()
        except httpx.HTTPError as exc:
            raise SourceError(f"download of {self.settings.target} failed: {exc}") from exc
        soup = BeautifulSoup(response.text, "html.parser")
        items = [el.get_text(" ", strip=True) for el in soup.select(self.selector)]
        items = [text for text in items if text][:50]
        title = soup.title.get_text(strip=True) if soup.title else ""
        return make_record(float(len(items)), {"url": self.settings.target, "title": title,
                                               "selector": self.selector, "items": items})

    async def aclose(self) -> None:
        """Close the HTTP connection pool."""
        await self._http.aclose()
''')

_CLIENT_JSON = Template('''

class ${client}:
    """Polls a JSON HTTP API and extracts one number from the reply."""

    def __init__(self, settings: Settings) -> None:
        """Create the HTTP client; API_TOKEN, when set, is sent as a bearer token."""
        self.settings = settings
        self.field_path = os.environ.get("VALUE_FIELD", "stargazers_count")
        headers = {"Accept": "application/json", "User-Agent": "${slug}/1.0"}
        token = os.environ.get("API_TOKEN", "")
        if token:
            headers["Authorization"] = f"Bearer {token}"
        self._http = httpx.AsyncClient(timeout=settings.timeout_seconds, headers=headers)

    async def fetch(self) -> dict[str, Any]:
        """Return the tracked value from ``settings.target`` as a record."""
        try:
            response = await self._http.get(self.settings.target)
            response.raise_for_status()
            body = response.json()
        except (httpx.HTTPError, ValueError) as exc:
            raise SourceError(f"request to {self.settings.target} failed: {exc}") from exc
        value = self._extract(body)
        return make_record(value, {"url": self.settings.target, "field": self.field_path})

    def _extract(self, body: Any) -> float:
        """Walk a dotted path such as ``data.0.price`` and return it as a float."""
        current = body
        for part in self.field_path.split("."):
            if isinstance(current, list) and part.isdigit() and int(part) < len(current):
                current = current[int(part)]
            elif isinstance(current, dict) and part in current:
                current = current[part]
            else:
                raise SourceError(f"field {self.field_path!r} not found in the response")
        try:
            return float(current)
        except (TypeError, ValueError) as exc:
            raise SourceError(f"field {self.field_path!r} is not a number: {current!r}") from exc

    async def aclose(self) -> None:
        """Close the HTTP connection pool."""
        await self._http.aclose()
''')

_CLIENT_DATASET = Template('''

class ${client}:
    """Loads a CSV dataset and trains and scores a scikit-learn ${task} model on it."""

    def __init__(self, settings: Settings) -> None:
        """Read the column to predict from TARGET_COLUMN."""
        self.settings = settings
        self.target_column = os.environ.get("TARGET_COLUMN", "target")

    async def fetch(self) -> dict[str, Any]:
        """Train on ``settings.target`` in a worker thread and return the score."""
        path = Path(self.settings.target)
        if not path.is_file():
            raise SourceError(f"dataset not found: {path} (set ${target_env})")
        try:
            score, rows = await asyncio.to_thread(self._train, path)
        except (OSError, ValueError, KeyError) as exc:
            raise SourceError(f"training on {path} failed: {exc}") from exc
        return make_record(score, {"dataset": str(path), "rows": rows,
                                   "target": self.target_column, "metric": "${metric}"})

    def _train(self, path: Path) -> tuple[float, int]:
        """Blocking part: read, split, fit and score. Runs off the event loop."""
        frame = pd.read_csv(path).dropna()
        if self.target_column not in frame.columns:
            raise KeyError(f"column {self.target_column!r} is not in the dataset")
        features = frame.drop(columns=[self.target_column]).select_dtypes("number")
        if features.empty:
            raise ValueError("the dataset has no numeric feature columns")
        target = frame[self.target_column]
        x_train, x_test, y_train, y_test = train_test_split(
            features, target, test_size=0.25, random_state=42)
        model = ${estimator}(n_estimators=200, random_state=42)
        model.fit(x_train, y_train)
        return float(model.score(x_test, y_test)), int(len(frame))

    async def aclose(self) -> None:
        """Nothing to release; present so every source has the same interface."""
''')

_CLIENT_FILES = Template('''

class ${client}:
    """Scans a folder and reports how many files it holds and their total size."""

    def __init__(self, settings: Settings) -> None:
        """Read the glob of files to include from FILE_PATTERN."""
        self.settings = settings
        self.pattern = os.environ.get("FILE_PATTERN", "*")

    async def fetch(self) -> dict[str, Any]:
        """Scan ``settings.target`` in a worker thread and return a summary record."""
        root = Path(self.settings.target).expanduser()
        if not root.is_dir():
            raise SourceError(f"folder not found: {root} (set ${target_env})")
        try:
            files = await asyncio.to_thread(self._scan, root)
        except OSError as exc:
            raise SourceError(f"scanning {root} failed: {exc}") from exc
        total = sum(size for _, size, _ in files)
        newest = sorted(files, key=lambda item: item[2], reverse=True)[:10]
        return make_record(float(total), {"folder": str(root), "files": len(files),
                                          "newest": [name for name, _, _ in newest]})

    def _scan(self, root: Path) -> list[tuple[str, int, float]]:
        """Blocking part: walk the tree and stat each matching file."""
        results: list[tuple[str, int, float]] = []
        for path in root.rglob(self.pattern):
            if path.is_file():
                stat = path.stat()
                results.append((str(path.relative_to(root)), stat.st_size, stat.st_mtime))
        return results

    async def aclose(self) -> None:
        """Nothing to release; present so every source has the same interface."""
''')

_CLIENTS = {"rpc": _CLIENT_RPC, "html": _CLIENT_HTML, "json": _CLIENT_JSON,
            "dataset": _CLIENT_DATASET, "files": _CLIENT_FILES}

_RPC = {
    "solana": {"chain": "Solana", "rpc_env": "SOLANA_RPC_URL",
               "rpc_default": "https://api.mainnet-beta.solana.com", "rpc_method": "getBalance",
               "rpc_params": "[self.settings.target]",
               "rpc_extract": 'int(body["result"]["value"])', "rpc_divisor": "1_000_000_000",
               "rpc_unit": "SOL"},
    "ethereum": {"chain": "Ethereum", "rpc_env": "ETH_RPC_URL",
                 "rpc_default": "https://ethereum-rpc.publicnode.com",
                 "rpc_method": "eth_getBalance", "rpc_params": '[self.settings.target, "latest"]',
                 "rpc_extract": 'int(body["result"], 16)', "rpc_divisor": "10**18",
                 "rpc_unit": "ETH"},
}


class _Layout:
    """The names and options a template render needs, derived from a spec."""

    def __init__(self, spec: SubAgentSpec) -> None:
        """Resolve profile, flags and class roles from ``spec``."""
        self.spec = spec
        notes = dict(n.split("=", 1) for n in spec.notes if "=" in n)
        self.profile: Profile = next((p for p in PROFILES if p.domain == spec.domain), None) \
            or choose_profile(spec.command) or DEFAULT_PROFILE
        self.fetch = notes.get("fetch", self.profile.fetch)
        if self.fetch not in _CLIENTS:
            self.fetch = self.profile.fetch
        self.rpc = notes.get("rpc", "solana") if notes.get("rpc") in _RPC else "solana"
        self.task = notes.get("task", "regression")
        self.wants_plot = "matplotlib" in spec.import_names

        def role(method: str, default: str) -> str:
            found = next((c.name for c in spec.classes if method in c.methods), "")
            return found or default

        self.client = role("fetch", self.profile.client)
        self.store = role("append", self.profile.store)
        self.plotter = role("plot", self.profile.plotter)
        self.main = role("run_once", "".join(p.capitalize() for p in spec.slug.split("_")))
        self.interval = spec.schedule_seconds or self.profile.interval

    def third_party_imports(self) -> str:
        """Import lines for exactly the libraries this layout uses."""
        lines: list[str] = []
        if self.fetch in ("rpc", "html", "json"):
            lines.append("import httpx")
        if self.fetch == "html":
            lines.append("from bs4 import BeautifulSoup")
        if self.fetch == "dataset" or self.wants_plot:
            lines.append("import pandas as pd")
        if self.fetch == "dataset":
            estimator = self.estimator
            lines.append(f"from sklearn.ensemble import {estimator}")
            lines.append("from sklearn.model_selection import train_test_split")
        if self.wants_plot:
            lines += ["import matplotlib", "", 'matplotlib.use("Agg")  # headless backend',
                      "", "import matplotlib.pyplot as plt  # noqa: E402"]
        return "\n".join(lines)

    @property
    def estimator(self) -> str:
        """scikit-learn estimator class for the dataset profile."""
        return ("RandomForestClassifier" if self.task == "classification"
                else "RandomForestRegressor")

    @property
    def third_party_modules(self) -> list[str]:
        """Top-level modules the generated agent imports (for importorskip in tests)."""
        mods = []
        if self.fetch in ("rpc", "html", "json"):
            mods.append("httpx")
        if self.fetch == "html":
            mods.append("bs4")
        if self.fetch == "dataset" or self.wants_plot:
            mods.append("pandas")
        if self.fetch == "dataset":
            mods.append("sklearn")
        if self.wants_plot:
            mods.append("matplotlib")
        return mods

    def values(self) -> dict[str, str]:
        """Substitution values shared by every template."""
        spec = self.spec
        summary_line = " ".join(spec.summary.split())
        short = summary_line if len(summary_line) <= 70 else summary_line[:67] + "..."
        values = {
            "name": spec.name, "slug": spec.slug, "upper": spec.slug.upper(),
            "summary_line": summary_line.replace('"""', "'''"),
            "summary_short": short.replace('"', "'"),
            "command": spec.command.replace('"""', "'''"),
            "run_example": spec.run_example,
            "run_forever": spec.run_example.replace(" --once", ""),
            "interval": str(self.interval),
            "target_env": self.profile.target_env,
            "default_target": self.profile.default_target,
            "value_label": self.profile.value_label,
            "client": self.client, "store": self.store, "plotter": self.plotter,
            "main": self.main,
            "plotter_type": f"{self.plotter} | None" if self.wants_plot else "Any | None",
            "plotter_ctor": (f'{self.plotter}(settings.data_dir / "chart.png", "{spec.name}")'
                             if self.wants_plot else "None"),
            "plot_note": " and chart" if self.wants_plot else "",
            "third_party": self.third_party_imports(),
            "task": self.task, "estimator": self.estimator,
            "metric": "accuracy" if self.task == "classification" else "r2",
        }
        values.update(_RPC[self.rpc])
        return values


def render_agent(spec: SubAgentSpec) -> str:
    """Render ``agent.py`` for ``spec`` from the built-in templates."""
    layout = _Layout(spec)
    values = layout.values()
    parts = [_HEADER.substitute(values), _CLIENTS[layout.fetch].substitute(values),
             _STORE.substitute(values)]
    if layout.wants_plot:
        parts.append(_PLOTTER.substitute(values))
    parts.append(_MAIN.substitute(values))
    code = "".join(parts)
    if not values["third_party"]:
        code = code.replace("from typing import Any\n\n\n\n", "from typing import Any\n\n")
    return code


_TESTS = Template('''\
"""Tests for the ${name} sub-agent.

They swap the real data source for a scripted fake, so they need no network
and no API key. Run them from this folder:

    python -m pytest -q
"""

from __future__ import annotations

import asyncio
from typing import Any

import pytest
${skips}
from agent import ${main}, ${store}, Settings, SourceError, make_record  # noqa: E402


class FakeSource:
    """A stand-in for the real data source that returns scripted values."""

    def __init__(self, values: list[Any]) -> None:
        """Queue the values (or exceptions) that ``fetch`` will produce."""
        self.values = list(values)
        self.closed = False

    async def fetch(self) -> dict[str, Any]:
        """Return the next scripted record, or raise the next scripted error."""
        value = self.values.pop(0)
        if isinstance(value, Exception):
            raise value
        return make_record(value, {"source": "fake"})

    async def aclose(self) -> None:
        """Record that the agent closed its source."""
        self.closed = True


def make_agent(tmp_path: Any, values: list[Any]) -> ${main}:
    """Build the agent around a fake source and a temporary history folder."""
    settings = Settings(target="test-target", interval_seconds=1, data_dir=tmp_path)
    return ${main}(settings, FakeSource(values), ${store}(tmp_path))


def test_settings_read_interval_from_env(monkeypatch: pytest.MonkeyPatch) -> None:
    """${upper}_INTERVAL overrides the default schedule."""
    monkeypatch.setenv("${upper}_INTERVAL", "7")
    assert Settings.from_env().interval_seconds == 7


def test_store_round_trip(tmp_path: Any) -> None:
    """A stored record reads back unchanged."""
    store = ${store}(tmp_path)
    record = make_record(1.5, {"key": "value"})
    store.append(record)
    assert store.load() == [record]
    assert store.last() == record


def test_run_once_records_only_changes(tmp_path: Any) -> None:
    """An unchanged reading is skipped; a changed one is stored."""
    agent = make_agent(tmp_path, [1.0, 1.0, 2.0])
    first = asyncio.run(agent.run_once())
    second = asyncio.run(agent.run_once())
    third = asyncio.run(agent.run_once())
    assert first is not None
    assert second is None
    assert third is not None and third["value"] == 2.0
    assert [r["value"] for r in agent.store.load()] == [1.0, 2.0]


def test_fetch_failure_is_logged_not_raised(tmp_path: Any,
                                            caplog: pytest.LogCaptureFixture) -> None:
    """A failing source is logged and nothing is written."""
    agent = make_agent(tmp_path, [SourceError("source is down")])
    with caplog.at_level("ERROR"):
        assert asyncio.run(agent.run_once()) is None
    assert "source is down" in caplog.text
    assert agent.store.load() == []
''')


def render_tests(spec: SubAgentSpec) -> str:
    """Render ``test_agent.py`` for ``spec``."""
    layout = _Layout(spec)
    values = layout.values()
    skips = "".join(f'\npytest.importorskip("{m}")' for m in layout.third_party_modules)
    values["skips"] = skips + ("\n" if skips else "")
    return _TESTS.substitute(values)


def render_readme(spec: SubAgentSpec, *, provider_label: str = "") -> str:
    """Render the sub-agent's README.md from its spec."""
    deps = "\n".join(f"- `{d.package}` — {d.purpose or 'runtime dependency'}"
                     for d in spec.dependencies) or "- none beyond the standard library"
    pip_line = " ".join(d.package for d in spec.dependencies)
    env_rows = "\n".join(
        f"| `{e.name}` | {'yes' if e.required else 'no'} | {e.purpose} |" for e in spec.env_vars
    ) or "| — | — | no environment variables |"
    classes = "\n".join(f"- **{c.name}** — {c.responsibility or 'see docstring'}"
                        + (f" (`{'`, `'.join(c.methods)}`)" if c.methods else "")
                        for c in spec.classes)
    keys = [e.name for e in spec.env_vars if e.required]
    key_line = (f"It needs `{'`, `'.join(keys)}` set before it can run."
                if keys else "It needs no API key; every setting has a default.")
    schedule = (f"every {spec.schedule_seconds} seconds" if spec.schedule_seconds
                else "on demand")
    install = f"pip install {pip_line}\n" if pip_line else ""
    origin = f" using `{provider_label}`" if provider_label else ""
    return textwrap.dedent(f"""\
        # {spec.name}

        {spec.summary}

        Generated by the [Father Agent](../../README.md){origin} from:

        > {spec.command}

        Domain: **{spec.domain}** · schedule: **{schedule}** · {key_line}

        ## Run it

        From the repository root:

        ```bash
        {install}{spec.run_example}          # one cycle, then exit
        {spec.run_example.replace(' --once', '')}   # keep running
        ```

        ## Configuration

        | Variable | Required | Purpose |
        | --- | --- | --- |
        {{env_rows}}

        ## Libraries

        {{deps}}

        ## How it is built

        {{classes}}

        ## Tests

        ```bash
        cd subagents/{spec.slug} && python -m pytest -q
        ```

        The tests use a fake data source: no network, no key.

        The Father Agent validated this code (ast, py_compile, ruff, imports) but
        never executed it. Read it before you run it; it is yours to change.
        """).replace("{env_rows}", env_rows).replace("{deps}", deps) \
        .replace("{classes}", classes)
